/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HabitId = IDL.Text;
export const Date = IDL.Text;
export const Completion = IDL.Record({
  'date' : Date,
  'completed' : IDL.Bool,
  'habitId' : HabitId,
});
export const Habit = IDL.Record({
  'id' : HabitId,
  'name' : IDL.Text,
  'createdAt' : Date,
  'color' : IDL.Text,
});

export const idlService = IDL.Service({
  'createHabit' : IDL.Func([IDL.Text, IDL.Text], [HabitId], []),
  'deleteHabit' : IDL.Func([HabitId], [IDL.Bool], []),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getHabitCompletions' : IDL.Func([HabitId], [IDL.Vec(Completion)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'markCompletion' : IDL.Func([HabitId, Date, IDL.Bool], [IDL.Bool], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateHabit' : IDL.Func([HabitId, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HabitId = IDL.Text;
  const Date = IDL.Text;
  const Completion = IDL.Record({
    'date' : Date,
    'completed' : IDL.Bool,
    'habitId' : HabitId,
  });
  const Habit = IDL.Record({
    'id' : HabitId,
    'name' : IDL.Text,
    'createdAt' : Date,
    'color' : IDL.Text,
  });
  
  return IDL.Service({
    'createHabit' : IDL.Func([IDL.Text, IDL.Text], [HabitId], []),
    'deleteHabit' : IDL.Func([HabitId], [IDL.Bool], []),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getHabitCompletions' : IDL.Func(
        [HabitId],
        [IDL.Vec(Completion)],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'markCompletion' : IDL.Func([HabitId, Date, IDL.Bool], [IDL.Bool], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateHabit' : IDL.Func([HabitId, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };